//
//  converterInteractor.swift
//  currency trip
//
//  Created by Guillermo Costa on 6/2/19.
//  Copyright (c) 2019 Guillermo Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


protocol ConverterBusinessLogic
{
  func doSomething(request: Converter.Something.Request)
}

protocol ConverterDataStore
{
  //var name: String { get set }
}

class ConverterInteractor: ConverterBusinessLogic, ConverterDataStore
{
  var presenter: ConverterPresentationLogic?
  var worker: ConverterWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Converter.Something.Request)
  {
    worker = ConverterWorker()
    worker?.doSomeWork()
    
    let response = Converter.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
