//
//  converterModels.swift
//  currency trip
//
//  Created by Guillermo Costa on 6/2/19.
//  Copyright (c) 2019 Guillermo Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


enum Currency {
    
    enum Fetch {
    
        enum State {
            case error(_: String)
            case success(response: [ViewModel])
        }

        struct Request: Codable {}

        struct Response: Codable {
            var id: Int
            var code: String
            var image: String?
            var name: String
            var value: Float
            
            enum CodingKeys: String, CodingKey {
                case id
                case code
                case image = "image_name"
                case name
                case value
            }
        }

        struct ViewModel {
            var id: Int
            var code: String
            var image: String?
            var name: String
            var value: Float
            var convertedValue: Float?
            
            init(with response: Response) {
                id = response.id
                code = response.code
                image = response.image ?? ""
                name = response.name
                value = response.value
            }
            
            mutating func convertValue(with value: Float) {
                convertedValue = value
            }
        }
    }
}
