//
//  converterRouter.swift
//  currency trip
//
//  Created by Guillermo Costa on 6/2/19.
//  Copyright (c) 2019 Guillermo Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ConverterRoutingLogic {
    func routeToCurrencies(segue: UIStoryboardSegue?)
}

protocol ConverterDataPassing {
    var dataStore: ConverterDataStore? { get }
}

class ConverterRouter: NSObject, ConverterRoutingLogic, ConverterDataPassing {
    
    weak var viewController: ConverterViewController?
    var dataStore: ConverterDataStore?
  
    func routeToCurrencies(segue: UIStoryboardSegue?) {
        guard let segue = segue, let destinationVC = segue.destination as? CurrenciesViewController else { return }
    }
    
}
