//
//  converterPresenter.swift
//  currency trip
//
//  Created by Guillermo Costa on 6/2/19.
//  Copyright (c) 2019 Guillermo Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


protocol ConverterPresentationLogic
{
  func presentSomething(response: Converter.Something.Response)
}

class ConverterPresenter: ConverterPresentationLogic
{
  weak var viewController: ConverterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Converter.Something.Response)
  {
    let viewModel = Converter.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
