//
//  converterRouter.swift
//  currency trip
//
//  Created by Guillermo Costa on 6/2/19.
//  Copyright (c) 2019 Guillermo Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ConverterRoutingLogic {
    func routeToCurrencies(segue: UIStoryboardSegue?)
}

protocol ConverterDataPassing {
    var dataStore: ConverterDataStore? { get }
}

class ConverterRouter: NSObject, ConverterRoutingLogic, ConverterDataPassing {
    
    weak var viewController: ConverterViewController?
    var dataStore: ConverterDataStore?
  
    // MARK: Routing
  
    func routeToCurrencies(segue: UIStoryboardSegue?) {
            guard let segue = segue, let destinationVC = segue.destination as? CurrenciesViewController else { return }
//            TODO COMPLETE ONLY THE IF (NOT ELSE)
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
        
//        O tmbn así
//        if let segue = segue {
//            let destinationVC = segue.destination as! CurrenciesViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            destinationVC.modalPresentationStyle = UIModalPresentationStyle.overCurrentContext
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        }
    }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: converterViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
    func passDataToSomewhere(source: ConverterDataStore, destination: inout CurrenciesDataStore) {
        destination.currencies = source.currencies
//        destination.name = source.name
    }
}
