//
//  converterPresenter.swift
//  currency trip
//
//  Created by Guillermo Costa on 6/2/19.
//  Copyright (c) 2019 Guillermo Costa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


protocol ConverterPresentationLogic {
    
    func presentCurrencies(viewModel: [Currency.Fetch.ViewModel])
    func presentConvertedCurrencies(viewModel: [Currency.Fetch.ViewModel])
    func presentCurrenciesFetchingError(response: String)
//    func convertCurrency(response: Currency.Fetch.Response)
}

class ConverterPresenter: ConverterPresentationLogic {
    
    weak var viewController: ConverterDisplayLogic?
    
    func presentCurrencies(viewModel: [Currency.Fetch.ViewModel]) {
        viewController?.displayCurrencies(viewModel: viewModel)
    }
    
    func presentConvertedCurrencies(viewModel: [Currency.Fetch.ViewModel]) {
//        TODO
    }
    
    func presentCurrenciesFetchingError(response: String) {
        viewController?.displayCurrenciesFetchingError(response: "ErrorData".localizedCapitalized)
    }
}
